server:
  port: 8080

spring:
  thymeleaf:
    prefix:
      classpath:/templates
    cache: false
  application:
    name: teamwork
  datasource:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/formal?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 923804049
