server:
  port: 8080

spring:
  thymeleaf:
    prefix:
      classpath:/templates
    cache: false
  application:
    name: teamwork
  datasource:
    driver_class_name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.183.98:3306/we?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 923804049
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapping/*.xml,classpath:mapping/ext/*.xml
  type-aliases-package: com.hg.teamwork.model

      