package com.hg.teamwork.rds.mapper;

import com.hg.teamwork.rds.model.InvitationCode;
import com.hg.teamwork.rds.model.InvitationCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvitationCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    long countByExample(InvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int deleteByExample(InvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int insert(InvitationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int insertSelective(InvitationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    List<InvitationCode> selectByExample(InvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    InvitationCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InvitationCode record, @Param("example") InvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InvitationCode record, @Param("example") InvitationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InvitationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invitation_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InvitationCode record);
}