package com.hg.teamwork.rds.mapper;

import com.hg.teamwork.rds.model.LearningMaterials;
import com.hg.teamwork.rds.model.LearningMaterialsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LearningMaterialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    long countByExample(LearningMaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    int deleteByExample(LearningMaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    int insert(LearningMaterials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    int insertSelective(LearningMaterials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    List<LearningMaterials> selectByExample(LearningMaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    LearningMaterials selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LearningMaterials record, @Param("example") LearningMaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LearningMaterials record, @Param("example") LearningMaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LearningMaterials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_materials
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LearningMaterials record);
}