package com.hg.teamwork.rds.mapper;

import com.hg.teamwork.rds.model.UserMst;
import com.hg.teamwork.rds.model.UserMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    long countByExample(UserMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    int deleteByExample(UserMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    int insert(UserMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    int insertSelective(UserMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    List<UserMst> selectByExample(UserMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    UserMst selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserMst record, @Param("example") UserMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserMst record, @Param("example") UserMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserMst record);
}