package com.hg.teamwork.mapper;

import com.hg.teamwork.model.Takeaway;
import com.hg.teamwork.model.TakeawayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TakeawayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    long countByExample(TakeawayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    int deleteByExample(TakeawayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    int insert(Takeaway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    int insertSelective(Takeaway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    List<Takeaway> selectByExample(TakeawayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    Takeaway selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Takeaway record, @Param("example") TakeawayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Takeaway record, @Param("example") TakeawayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Takeaway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takeaway
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Takeaway record);
}