package com.hg.teamwork.rds.model;

public class InvitationCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invitation_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.id
     *
     * @return the value of invitation_code.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.id
     *
     * @param id the value for invitation_code.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invitation_code.code
     *
     * @return the value of invitation_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invitation_code.code
     *
     * @param code the value for invitation_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}