package com.hg.teamwork.rds.model;

import java.util.Date;

public class LearningMaterials {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_materials.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_materials.profile_name
     *
     * @mbg.generated
     */
    private String profileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_materials.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_materials.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_materials.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_materials.id
     *
     * @return the value of learning_materials.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_materials.id
     *
     * @param id the value for learning_materials.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_materials.profile_name
     *
     * @return the value of learning_materials.profile_name
     *
     * @mbg.generated
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_materials.profile_name
     *
     * @param profileName the value for learning_materials.profile_name
     *
     * @mbg.generated
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName == null ? null : profileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_materials.path
     *
     * @return the value of learning_materials.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_materials.path
     *
     * @param path the value for learning_materials.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_materials.user_id
     *
     * @return the value of learning_materials.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_materials.user_id
     *
     * @param userId the value for learning_materials.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_materials.create_time
     *
     * @return the value of learning_materials.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_materials.create_time
     *
     * @param createTime the value for learning_materials.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}