package com.hg.teamwork.rds.model;

import java.util.Date;

public class Takeaway {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takeaway.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takeaway.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takeaway.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takeaway.id
     *
     * @return the value of takeaway.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takeaway.id
     *
     * @param id the value for takeaway.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takeaway.name
     *
     * @return the value of takeaway.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takeaway.name
     *
     * @param name the value for takeaway.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takeaway.time
     *
     * @return the value of takeaway.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takeaway.time
     *
     * @param time the value for takeaway.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}